In [1]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(f"a: {str(a.tolist()):>69}\n"
      f"Shape of a: {str(a.shape):>10}\n"
      f"Dims of a: {str(a.ndim):>10}\n"
      f"Data type of a: {str(a.dtype.name):>9}\n"
      f"Item size a: {str(a.itemsize):>10}\n"
      f"Size of a: {str(a.size):>10}\n"
      f"type of a: {str(type(a)):>10}\n"
     )

a:              [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
Shape of a:     (3, 5)
Dims of a:          2
Data type of a:     int64
Item size a:          8
Size of a:         15
type of a: <class 'numpy.ndarray'>



In [2]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [3]:
zeros = np.zeros((3,4)) # All Zeros
ones = np.ones((2,3,4)) # All Ones
empty = np.empty((2,3)) # Random elements, based on memory

print(f"zeros:{zeros}\n"  
      f"ones:{ones}\n"
      f"empty:{empty}\n"
     )

zeros:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
empty:[[1.5 2.  3. ]
 [4.  5.  6. ]]

