In [1]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(f"a: {str(a.tolist()):>69}\n"
      f"Shape of a: {str(a.shape):>10}\n"
      f"Dims of a: {str(a.ndim):>10}\n"
      f"Data type of a: {str(a.dtype.name):>9}\n"
      f"Item size a: {str(a.itemsize):>10}\n"
      f"Size of a: {str(a.size):>10}\n"
      f"type of a: {str(type(a)):>10}\n"
     )

a:              [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
Shape of a:     (3, 5)
Dims of a:          2
Data type of a:     int64
Item size a:          8
Size of a:         15
type of a: <class 'numpy.ndarray'>



In [2]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [3]:
zeros = np.zeros((3,4)) # All Zeros
ones = np.ones((2,3,4)) # All Ones
empty = np.empty((2,3)) # Random elements, based on memory

print(f"zeros:{zeros}\n"  
      f"ones:{ones}\n"
      f"empty:{empty}\n"
     )

zeros:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
empty:[[1.5 2.  3. ]
 [4.  5.  6. ]]



In [4]:
#arange
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [5]:
#linspace
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
